### PR TITLE
render "?" for winstreak when api disabled

### PR DESCRIPTION
**Pull request by Arjun99ab**

### CODE REVIEW

**Comment by amosyu2000** [comment]
@Arjun99ab Thanks for doing this, do you have screenshots of what you modified?

**Comment by Arjun99ab** [comment]
image
image
image

**Review by amosyu2000 — CHANGES_REQUESTED** [review]
Seems like there's a lot of duplicated logic in the PR. Could you please refactor into a function called `defaultUnknown(val)`? You can put the function in `utils/index.js`.

**Comment by Arjun99ab** [comment]
Thanks, I'll keep this in mind for future potential PRs

**Review by amosyu2000 — APPROVED** [review]
lgtm!

**Pull request merged**
